on:
  push:
    branches:
      - main

jobs:
  build:
    name: build app
    runs-on: ubuntu-latest
    steps:
      - name: menampilkan teks
        run: echo "ini step build"
  test:
    name: test app
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: menampilkan teks
        run: echo "ini step test"
  deploy:
    name: deploy app
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: menampilkan teks
        run: echo "ini step deploy"
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 119.81.221.29
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: /
            id
            rm -rf git-demo-devops
            git clone https://github.com/alvinsenjaya/git-demo-devops
            cp git-demo-devops/* /var/www/html
            rm -rf git-demo-devops
