on:
  push:
    branches:
      - main

jobs:
  build:
    name: build app
    runs-on: ubuntu-latest
    steps:
      - name: menampilkan teks
        run: echo "ini step build"
  test:
    name: test app
    runs-on: ubuntu-latest
    steps:
      - name: menampilkan teks
        run: echo "ini step test"
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    steps:
      - name: menampilkan teks
        run: echo "ini step deploy"
